User.create(email: 'timyates@gmail.com', password: 'timyates')
User.create(email: 'markthompson@gmail.com', password: 'markthompson')
User.create(email: 'johnhamlin@gmail.com', password: 'johnhamlin')
User.create(email: 'brookejones@gmail.com', password: 'brookejones')
User.create(email: 'alisonchristine@gmail.com', password: 'alisonchristine')


Card.create!(question: 'What is the center of the atom called?', answer: 'The nucleus', mastery: 2)
Card.create!(question: 'At room temperature, what is the only metal in liquid form?', answer: 'mercury')
Card.create!(question: 'Is sodium hydroxide (NaOH) an acid or base?', answer: 'base', mastery: 5)
Card.create!(question: 'The great Victoria Desert is located in...?', answer: 'Australia')
Card.create!(question: 'Name the 5 Great Lakes in the U.S.', answer: 'Lakes Superior, Michigan, Huron, Erie, and Ontario')
Card.create!(question: 'What is the capital of Albania', answer: 'Tirana')
Card.create!(question: 'What was the name of the company Steve Jobs founded after getting fired from Apple?', answer: 'NeXT')
Card.create!(question: 'What was the original inspiration for the Mac\'s GUI?', answer: 'Steve Jobs visit to Xerox PARC in 1979')
Card.create!(question: 'What American electrical engineer is known as the \'father of information theory\'', answer: 'Claude Shannon')
Card.create!(question: 'This person created a machine called The Analytical Engine. His ideas were some of the first that led to the creation of computers', answer: 'Charles Babbage')
Card.create!(question: 'Who led the Manhatten Project?', answer: 'Robert Oppenheimer', mastery: 5)
