User.create(email: 'timyates@gmail.com', password: 'timyates')
User.create(email: 'markthompson@gmail.com', password: 'markthompson')
User.create(email: 'johnhamlin@gmail.com', password: 'johnhamlin')
User.create(email: 'brookejones@gmail.com', password: 'brookejones')
User.create(email: 'alisonchristine@gmail.com', password: 'alisonchristine')
